name: Build Json

on: 
  workflow_dispatch:
#  schedule:
#    - cron: '15 6 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    container: php
    steps:
#    - uses: actions/checkout@v3
#      with:
#        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
#        persist-credentials: true
    - name: Commit files
      run: |
        mkdir ~/.ssh
        echo ${{ secrets.SSH_PUBLIC_KEY }} > ~/.ssh/id_rsa.pub
        chmod -R 700 ~/.ssh
        ls -la
        pwd
        whoami
