name: Build Json

on: 
  workflow_dispatch:
#  schedule:
#    - cron: '15 6 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    container: php
    steps:
#    - uses: actions/checkout@v3
#      with:
#        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
#        persist-credentials: true
    - name: Commit files
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod -R 700 ~/.ssh
        cat ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa.pub
#        apt update; apt -fy install git
#        git clone https://github.com/fbraz3/publicsuffix-json-generator.git .
#        ls -la ~
#        ls -la ~/.ssh
#        git clone git@github.com:fbraz3/publicsuffix-json.git repo
#        ls -la
