name: Build Json

on: 
  workflow_dispatch:
#  schedule:
#    - cron: '15 6 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    container: php
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
    - name: Setup GIT
      run: |
        git config --global user.email "fbraz3@gmail.com"
        git config --global user.name "Felipe Braz"
    - name: Install packages
      run: |
        apt update; apt -fy install git wget curl
    - name: Clone Repo
      run: |
        apt update; apt -fy install git
        git clone https://github.com/fbraz3/publicsuffix-json-generator.git .
        git clone git@github.com:fbraz3/publicsuffix-json.git repo
    - name: Deploy Json
      run: |
        php build.php
