name: Build Json

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: php
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
    - name: Install packages
      run: |
        apt update; apt -fy install git wget curl
    - name: Setup GIT
      run: |
        export GIT_USER=${{secrets.GIT_USER}}
        export GIT_EMAIL=${{secrets.GIT_EMAIL}}
        git config --global user.name "$GIT_USER"
        git config --global user.email "$GIT_EMAIL"
    - name: Clone Repo
      run: |
        ssh-keygen -f "/root/.ssh/known_hosts" -R "github.com"
        ssh-keygen -F github.com || ssh-keyscan github.com >> /root/.ssh/known_hosts
        git clone https://github.com/fbraz3/publicsuffix-json-generator.git .
        git clone git@github.com:fbraz3/publicsuffix-json.git repo
    - name: Deploy Json
      run: |
        php build.php
